name: Deploy Laravel Application to Production Server v2
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Flushing remote folder except .env and storage
        continue-on-error: true
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ -d "${{ vars.SSH_PATH }}" ]; then
              cd ${{ vars.SSH_PATH }}
              find . -mindepth 1 ! -path './storage/*' ! -name '.env' ! -name 'storage' -exec rm -rf {} +
            else
              echo "Error: Directory ${{ vars.SSH_PATH }} does not exist!" >&2
              exit 1
            fi
